# Generated by Django 3.1 on 2020-09-16 15:20

from django.db import migrations
import wagtailmd.utils


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_standardpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtailmd.utils.MarkdownField(),
        ),
    ]
